export const TODOS_REQUEST = 'TODOS_REQUEST';
export const TODOS_REQUEST_SUCCESS = 'TODOS_REQUEST_SUCCESS';
export const TODOS_REQUEST_FAILURE = 'TODOS_REQUEST_FAILURE';
export const TODO_CREATE_UPDATE_REQUEST = 'TODO_CREATE_UPDATE_REQUEST';