export const START_REQUEST = 'START_REQUEST';
export const TODOS_REQUEST_SUCCESS = 'TODOS_REQUEST_SUCCESS';
export const TODOS_REQUEST_FAILURE = 'TODOS_REQUEST_FAILURE';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';